export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE';
export const GET_NEWS_DATA = 'GET_NEWS_DATA';
export const GET_NEWS_DATA_SUCCESS = 'GET_NEWS_DATA_SUCCESS';
export const GET_NEWS_DATA_FAILURE = 'GET_NEWS_DATA_FAILURE';